---
- name: Test WinRM
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show hostname
      ansible.windows.win_shell: hostname
      register: hostname

    - name: Print hostname
      debug:
        var: hostname.stdout
